import { Prescription } from '@/types';
import { createStore } from './createStore';

const mockPrescriptions: Prescription[] = [
  {
    id: 'rx-1',
    patientId: 'pt-1',
    doctorId: 'u-2',
    visitId: 'v-1',
    status: 'active',
    medications: [
      {
        id: 'med-1',
        name: 'Lisinopril',
        nameAr: 'ليسينوبريل',
        dosage: '10mg',
        frequency: 'once_daily',
        duration: '90 days',
        instructions: 'Take in the morning with water',
        instructionsAr: 'يؤخذ صباحاً مع الماء',
        refillsTotal: 3,
        refillsUsed: 1,
        nextRefillDate: '2026-04-01',
      },
      {
        id: 'med-2',
        name: 'Aspirin',
        nameAr: 'أسبرين',
        dosage: '81mg',
        frequency: 'once_daily',
        duration: '90 days',
        instructions: 'Take with food',
        instructionsAr: 'يؤخذ مع الطعام',
        refillsTotal: 3,
        refillsUsed: 1,
        nextRefillDate: '2026-04-01',
      },
    ],
    notes: 'Monitor blood pressure weekly',
    prescribedAt: '2026-01-15',
    expiresAt: '2026-07-15',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'rx-2',
    patientId: 'pt-1',
    doctorId: 'u-2',
    status: 'completed',
    medications: [
      {
        id: 'med-3',
        name: 'Amoxicillin',
        nameAr: 'أموكسيسيلين',
        dosage: '500mg',
        frequency: 'three_times_daily',
        duration: '10 days',
        instructions: 'Complete full course',
        instructionsAr: 'أكمل الجرعة كاملة',
        refillsTotal: 0,
        refillsUsed: 0,
      },
    ],
    prescribedAt: '2025-12-01',
    expiresAt: '2025-12-11',
    createdAt: '2025-12-01T09:00:00Z',
    updatedAt: '2025-12-11T09:00:00Z',
  },
  {
    id: 'rx-3',
    patientId: 'pt-3',
    doctorId: 'u-4',
    status: 'active',
    medications: [
      {
        id: 'med-4',
        name: 'Metformin',
        nameAr: 'ميتفورمين',
        dosage: '500mg',
        frequency: 'twice_daily',
        duration: '90 days',
        instructions: 'Take with meals',
        instructionsAr: 'يؤخذ مع الوجبات',
        refillsTotal: 4,
        refillsUsed: 2,
        nextRefillDate: '2026-03-15',
      },
    ],
    notes: 'Check HbA1c in 3 months',
    prescribedAt: '2026-01-10',
    expiresAt: '2026-07-10',
    createdAt: '2026-01-10T14:00:00Z',
    updatedAt: '2026-01-10T14:00:00Z',
  },
];

export const prescriptionStore = createStore<Prescription>(mockPrescriptions, 'cf_prescriptions');
